### ISSUE TITLE
Regex pattern doesn't match keys

### ISSUE THREAD

**Issue by pachnerEncor** [singer-io/tap-intacct#8]
https://github.com/singer-io/tap-intacct/blob/5ad74df15debead6c07d521e83e1d079c070cc10/tap_intacct/s3.py#L175C6-L175C6

I think this a typo in the pattern when tagging the ..csv to it. 

For example if my pattern =  "^stitch/Encor Revenues Inception To Date\..*\.csv" 
It will not match to my key = "stitch/Encor Revenues Inception To Date.csv"

HOWEVER when I remove the second "." before the "*" the pattern matches the key.

This is the error I receive within the stitch console. 
![image](https://github.com/singer-io/tap-intacct/assets/135995237/b93a1c64-1b62-4a5d-942d-d480c283ab89)
Even though in my S3 bucket there is a key that should match it 
![image](https://github.com/singer-io/tap-intacct/assets/135995237/a77aad8f-fdf2-44af-89ae-ecacb114966e)

testing the regex on pythex.org
Single period before the "*"
![image](https://github.com/singer-io/tap-intacct/assets/135995237/c9afb965-90b5-4274-a1c9-b7a0c32df0a5)

Double period before the "*"
![image](https://github.com/singer-io/tap-intacct/assets/135995237/c0594ebb-33d5-4d4b-83cd-bdeeb9d6ecf8)

**Comment by rdeshmukh15** [comment]
@pachnerEncor : Fixed the issue and released bump version 1.0.2.
Please have a look
